.PHONY: test-backend frontend frontend-build install start up docker-up stop docker-down restart update integrations integrations-build integrations-pull docker-prune

test-backend frontend frontend-build install start up docker-up stop docker-down restart update integrations integrations-build integrations-pull docker-prune:
	$(MAKE) -C .. $@
