.PHONY: test-backend frontend frontend-build install start up docker-up stop docker-down restart full full-build full-pull docker-prune

test-backend frontend frontend-build install start up docker-up stop docker-down restart full full-build full-pull docker-prune:
	$(MAKE) -C .. $@
